esphome:
  name: m5atom-advantage-air
  friendly_name: Advantage Air AC Controller

esp32:
  variant: ESP32
  framework:
    type: arduino

logger:
  baud_rate: 115200
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  id: rs485_bus
  tx_pin: GPIO19
  rx_pin: GPIO22
  baud_rate: 57600
  data_bits: 8
  stop_bits: 1
  parity: NONE
  debug:
    direction: RX
    dummy_receiver: true
    after:
      timeout: 1000ms
    sequence:
      - lambda: |-
          std::string response;
          for (auto c : bytes) {
            if (c >= 32 && c < 127) response += static_cast<char>(c);
            else if (c == '\r') response += "";
            else if (c == '\n') response += "";
          }
          ESP_LOGI("AC", "RX: %s", response.c_str());

globals:
  - id: ac_power
    type: bool
    initial_value: "false"
  - id: ac_mode
    type: int
    initial_value: "1"
  - id: ac_fan
    type: int
    initial_value: "1"
  - id: ac_temp
    type: float
    initial_value: "21.0"
  - id: zone1_temp
    type: float
    initial_value: "0.0"
  - id: zone1_open
    type: bool
    initial_value: "false"
  - id: zone1_rf
    type: int
    initial_value: "0"
  - id: zone2_temp
    type: float
    initial_value: "0.0"
  - id: zone2_open
    type: bool
    initial_value: "false"
  - id: zone2_rf
    type: int
    initial_value: "0"
  - id: zone3_temp
    type: float
    initial_value: "0.0"
  - id: zone3_open
    type: bool
    initial_value: "false"
  - id: zone3_rf
    type: int
    initial_value: "0"
  - id: zone7_temp
    type: float
    initial_value: "0.0"
  - id: zone7_open
    type: bool
    initial_value: "false"
  - id: zone7_rf
    type: int
    initial_value: "0"

sensor:
  - platform: uptime
    name: "Uptime"

  - platform: template
    name: "Kitchen Temperature"
    id: sensor_kitchen_temp
    unit_of_measurement: "째C"
    accuracy_decimals: 1
    lambda: return id(zone1_temp);

  - platform: template
    name: "Kitchen Signal"
    id: sensor_kitchen_signal
    unit_of_measurement: "%"
    lambda: return (float)id(zone1_rf);

  - platform: template
    name: "Master Temperature"
    id: sensor_master_temp
    unit_of_measurement: "째C"
    accuracy_decimals: 1
    lambda: return id(zone2_temp);

  - platform: template
    name: "Master Signal"
    id: sensor_master_signal
    unit_of_measurement: "%"
    lambda: return (float)id(zone2_rf);

  - platform: template
    name: "Guest Temperature"
    id: sensor_guest_temp
    unit_of_measurement: "째C"
    accuracy_decimals: 1
    lambda: return id(zone3_temp);

  - platform: template
    name: "Guest Signal"
    id: sensor_guest_signal
    unit_of_measurement: "%"
    lambda: return (float)id(zone3_rf);

  - platform: template
    name: "Theatre Temperature"
    id: sensor_theatre_temp
    unit_of_measurement: "째C"
    accuracy_decimals: 1
    lambda: return id(zone7_temp);

  - platform: template
    name: "Theatre Signal"
    id: sensor_theatre_signal
    unit_of_measurement: "%"
    lambda: return (float)id(zone7_rf);

text_sensor:
  - platform: template
    name: "Kitchen Vent"
    id: sensor_kitchen_vent
    lambda: return id(zone1_open) ? std::string("Open") : std::string("Closed");

  - platform: template
    name: "Master Vent"
    id: sensor_master_vent
    lambda: return id(zone2_open) ? std::string("Open") : std::string("Closed");

  - platform: template
    name: "Guest Vent"
    id: sensor_guest_vent
    lambda: return id(zone3_open) ? std::string("Open") : std::string("Closed");

  - platform: template
    name: "Theatre Vent"
    id: sensor_theatre_vent
    lambda: return id(zone7_open) ? std::string("Open") : std::string("Closed");

  - platform: template
    name: "AC Mode"
    id: sensor_ac_mode
    lambda: {
      switch(id(ac_mode)) {
        case 1: return std::string("Cool");
        case 2: return std::string("Heat");
        case 3: return std::string("Fan");
        default: return std::string("Off");
      }
    }

  - platform: template
    name: "Fan Speed"
    id: sensor_fan_speed
    lambda: {
      switch(id(ac_fan)) {
        case 1: return std::string("Low");
        case 2: return std::string("Medium");
        case 3: return std::string("High");
        default: return std::string("Auto");
      }
    }

switch:
  - platform: template
    name: "AC Power"
    id: switch_ac_power
    optimistic: true
    on_turn_on:
      - lambda: id(rs485_bus).write_str("<U>setSystemData?airconOnOff=1</U=XX>");
    on_turn_off:
      - lambda: id(rs485_bus).write_str("<U>setSystemData?airconOnOff=0</U=XX>");

  - platform: template
    name: "Zone 1"
    id: switch_zone1
    optimistic: true
    on_turn_on:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=1&setting=1</U=b6>");
    on_turn_off:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=1&setting=0</U=b7>");

  - platform: template
    name: "Zone 2"
    id: switch_zone2
    optimistic: true
    on_turn_on:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=2&setting=1</U=36>");
    on_turn_off:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=2&setting=0</U=37>");

  - platform: template
    name: "Zone 3"
    id: switch_zone3
    optimistic: true
    on_turn_on:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=3&setting=1</U=fe>");
    on_turn_off:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=3&setting=0</U=ff>");

  - platform: template
    name: "Zone 7"
    id: switch_zone7
    optimistic: true
    on_turn_on:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=7&setting=1</U=79>");
    on_turn_off:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=7&setting=0</U=7a>");

cover:
  - platform: template
    name: "Store"
    id: cover_store
    optimistic: true
    on_open:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=4&setting=1</U=3e>");
    on_closed:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=4&setting=0</U=3f>");

  - platform: template
    name: "Study"
    id: cover_study
    optimistic: true
    on_open:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=5&setting=1</U=be>");
    on_closed:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=5&setting=0</U=bf>");

  - platform: template
    name: "Workroom"
    id: cover_workroom
    optimistic: true
    on_open:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=6&setting=1</U=7e>");
    on_closed:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=6&setting=0</U=7f>");

select:
  - platform: template
    name: "AC Mode"
    id: select_ac_mode
    options:
      - "Cool"
      - "Heat"
      - "Fan"
    initial_option: "Cool"
    optimistic: true
    set_action:
      - lambda: |-
          int mode = 1;
          if (x == "Heat") mode = 2;
          else if (x == "Fan") mode = 3;
          std::string cmd = "<U>setSystemData?mode=" + to_string(mode) + "</U=XX>";
          id(rs485_bus).write_str(cmd.c_str());

  - platform: template
    name: "Fan Speed"
    id: select_fan_speed
    options:
      - "Low"
      - "Medium"
      - "High"
    initial_option: "Low"
    optimistic: true
    set_action:
      - lambda: |-
          int speed = 1;
          if (x == "Medium") speed = 2;
          else if (x == "High") speed = 3;
          std::string cmd = "<U>setSystemData?fanSpeed=" + to_string(speed) + "</U=XX>";
          id(rs485_bus).write_str(cmd.c_str());

  - platform: template
    name: "MyZone"
    id: select_myzones
    options:
      - "Kitchen"
      - "Master"
      - "Guest"
      - "Theatre"
    initial_option: "Kitchen"
    optimistic: true
    set_action:
      - lambda: |-
          int zone = 1;
          if (x == "Master") zone = 2;
          else if (x == "Guest") zone = 3;
          else if (x == "Theatre") zone = 7;
          std::string cmd = "<U>setMyZone?zone=" + to_string(zone) + "</U=XX>";
          id(rs485_bus).write_str(cmd.c_str());

number:
  - platform: template
    name: "Target Temperature"
    id: number_target_temp
    min_value: 16
    max_value: 30
    step: 0.5
    initial_value: 21
    optimistic: true
    set_action:
      - lambda: |-
          std::string cmd = "<U>setSystemData?centralDesiredTemp=" + to_string(x) + "</U=XX>";
          id(rs485_bus).write_str(cmd.c_str());

button:
  - platform: template
    name: "Refresh Status"
    on_press:
      - lambda: |-
          id(rs485_bus).write_str("<U>Ping</U=db>");
          delay(10);
          id(rs485_bus).write_str("<U>getSystemData</U=15>");

interval:
  - interval: 30s
    then:
      - lambda: |-
          id(rs485_bus).write_str("<U>Ping</U=db>");
          delay(10);
          id(rs485_bus).write_str("<U>getSystemData</U=15>");
          delay(30);
          id(rs485_bus).write_str("<U>getZoneData?zone=1</U=74>");
          delay(20);
          id(rs485_bus).write_str("<U>getZoneData?zone=2</U=36>");
          delay(20);
          id(rs485_bus).write_str("<U>getZoneData?zone=3</U=08>");
          delay(20);
          id(rs485_bus).write_str("<U>getZoneData?zone=7</U=f0>");
