esphome:
  name: m5atom-advantage-air
  friendly_name: Advantage Air AC Controller

esp32:
  variant: ESP32
  framework:
    type: arduino

logger:
  baud_rate: 115200
  level: INFO

api:
  encryption:
    key: !secret esphome_api_key

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  id: rs485_bus
  tx_pin: GPIO19
  rx_pin: GPIO22
  baud_rate: 57600
  data_bits: 8
  stop_bits: 1
  parity: NONE
  debug:
    direction: RX
    dummy_receiver: true
    after:
      timeout: 1000ms
    sequence:
      - lambda: |-
          std::string response;
          for (auto c : bytes) {
            if (c >= 32 && c < 127) response += static_cast<char>(c);
            else if (c == '\r') response += "\\r";
            else if (c == '\n') response += "\\n";
          }
          ESP_LOGI("AC", "RX: %s", response.c_str());

sensor:
  - platform: uptime
    name: "Uptime"

  - platform: template
    name: "Kitchen Signal"
    id: ac_zone1_signal
    unit_of_measurement: "%"

  - platform: template
    name: "Master Signal"
    id: ac_zone2_signal
    unit_of_measurement: "%"

  - platform: template
    name: "Guest Signal"
    id: ac_zone3_signal
    unit_of_measurement: "%"

  - platform: template
    name: "Theatre Signal"
    id: ac_zone7_signal
    unit_of_measurement: "%"

  - platform: template
    name: "Kitchen Temperature"
    id: kitchen_temp
    unit_of_measurement: "째C"
    accuracy_decimals: 1

  - platform: template
    name: "Master Temperature"
    id: master_temp
    unit_of_measurement: "째C"
    accuracy_decimals: 1

  - platform: template
    name: "Guest Temperature"
    id: guest_temp
    unit_of_measurement: "째C"
    accuracy_decimals: 1

  - platform: template
    name: "Theatre Temperature"
    id: theatre_temp
    unit_of_measurement: "째C"
    accuracy_decimals: 1

text_sensor:
  - platform: template
    name: "Kitchen Vent"
    id: ac_zone1_vent

  - platform: template
    name: "Master Vent"
    id: ac_zone2_vent

  - platform: template
    name: "Guest Vent"
    id: ac_zone3_vent

  - platform: template
    name: "Theatre Vent"
    id: ac_zone7_vent

  - platform: template
    name: "AC Mode"
    id: ac_mode_text

  - platform: template
    name: "Fan Speed"
    id: ac_fan_text

  - platform: template
    name: "Filter Status"
    id: ac_filter

binary_sensor:
  - platform: template
    name: "Filter"
    id: ac_filter_2

  - platform: template
    name: "AC Power"
    id: ac_power_sensor

switch:
  - platform: template
    name: "AC Power"
    id: ac_power
    optimistic: true
    on_turn_on:
      - lambda: id(rs485_bus).write_str("<U>setSystemData?airconOnOff=1</U=XX>");
    on_turn_off:
      - lambda: id(rs485_bus).write_str("<U>setSystemData?airconOnOff=0</U=XX>");

  - platform: template
    name: "Zone 1"
    id: switch_zone1
    optimistic: true
    on_turn_on:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=1&setting=1</U=b6>");
    on_turn_off:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=1&setting=0</U=b7>");

  - platform: template
    name: "Zone 2"
    id: switch_zone2
    optimistic: true
    on_turn_on:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=2&setting=1</U=36>");
    on_turn_off:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=2&setting=0</U=37>");

  - platform: template
    name: "Zone 3"
    id: switch_zone3
    optimistic: true
    on_turn_on:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=3&setting=1</U=fe>");
    on_turn_off:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=3&setting=0</U=ff>");

  - platform: template
    name: "Zone 4"
    id: switch_zone4
    optimistic: true
    on_turn_on:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=4&setting=1</U=3e>");
    on_turn_off:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=4&setting=0</U=3f>");

  - platform: template
    name: "Zone 5"
    id: switch_zone5
    optimistic: true
    on_turn_on:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=5&setting=1</U=be>");
    on_turn_off:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=5&setting=0</U=bf>");

  - platform: template
    name: "Zone 6"
    id: switch_zone6
    optimistic: true
    on_turn_on:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=6&setting=1</U=7e>");
    on_turn_off:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=6&setting=0</U=7f>");

  - platform: template
    name: "Zone 7"
    id: switch_zone7
    optimistic: true
    on_turn_on:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=7&setting=1</U=79>");
    on_turn_off:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=7&setting=0</U=7a>");

cover:
  - platform: template
    name: "Store"
    id: cover_store
    optimistic: true
    on_open:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=4&setting=1</U=3e>");
    on_close:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=4&setting=0</U=3f>");

  - platform: template
    name: "Study"
    id: cover_study
    optimistic: true
    on_open:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=5&setting=1</U=be>");
    on_close:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=5&setting=0</U=bf>");

  - platform: template
    name: "Workroom"
    id: cover_workroom
    optimistic: true
    on_open:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=6&setting=1</U=7e>");
    on_close:
      - lambda: id(rs485_bus).write_str("<U>setZoneData?zone=6&setting=0</U=7f>");

select:
  - platform: template
    name: "AC Mode"
    id: ac_mode
    options:
      - "Off"
      - "Cool"
      - "Heat"
      - "Fan"
    initial_option: "Cool"
    optimistic: true
    set_action:
      - lambda: |-
          int mode = 1;
          if (x == "Off") mode = 0;
          else if (x == "Heat") mode = 2;
          else if (x == "Fan") mode = 3;
          std::string cmd = "<U>setSystemData?mode=" + to_string(mode) + "</U=XX>";
          id(rs485_bus).write_str(cmd.c_str());

  - platform: template
    name: "Fan Speed"
    id: fan_speed
    options:
      - "Low"
      - "Medium"
      - "High"
    initial_option: "Low"
    optimistic: true
    set_action:
      - lambda: |-
          int speed = 1;
          if (x == "Medium") speed = 2;
          else if (x == "High") speed = 3;
          std::string cmd = "<U>setSystemData?fanSpeed=" + to_string(speed) + "</U=XX>";
          id(rs485_bus).write_str(cmd.c_str());

  - platform: template
    name: "MyZone"
    id: ac_myzone
    options:
      - "Kitchen"
      - "Master"
      - "Guest"
      - "Theatre"
      - "Store"
      - "Study"
      - "Workroom"
    initial_option: "Kitchen"
    optimistic: true
    set_action:
      - lambda: |-
          int zone = 1;
          if (x == "Master") zone = 2;
          else if (x == "Guest") zone = 3;
          else if (x == "Theatre") zone = 7;
          else if (x == "Store") zone = 4;
          else if (x == "Study") zone = 5;
          else if (x == "Workroom") zone = 6;
          std::string cmd = "<U>setMyZone?zone=" + to_string(zone) + "</U=XX>";
          id(rs485_bus).write_str(cmd.c_str());

number:
  - platform: template
    name: "Target Temperature"
    id: target_temp
    min_value: 16
    max_value: 30
    step: 0.5
    initial_value: 22
    optimistic: true
    set_action:
      - lambda: |-
          std::string cmd = "<U>setSystemData?centralDesiredTemp=" + to_string(x) + "</U=XX>";
          id(rs485_bus).write_str(cmd.c_str());

button:
  - platform: template
    name: "Refresh Status"
    on_press:
      - lambda: |-
          id(rs485_bus).write_str("<U>getSystemData</U=15>");

interval:
  - interval: 30s
    then:
      - lambda: |-
          id(rs485_bus).write_str("<U>getSystemData</U=15>");
          delay(30);
          id(rs485_bus).write_str("<U>getZoneData?zone=1</U=74>");
          delay(30);
          id(rs485_bus).write_str("<U>getZoneData?zone=2</U=36>");
          delay(30);
          id(rs485_bus).write_str("<U>getZoneData?zone=3</U=fe>");
          delay(30);
          id(rs485_bus).write_str("<U>getZoneData?zone=7</U=79>");
