esphome:
  name: m5atom-advantage-air
  friendly_name: Zone 6 Sniffer

esp32:
  board: m5stack-atom
  variant: ESP32
  framework:
    type: arduino

logger:
  baud_rate: 115200
  level: INFO

api:
  encryption:
    key: !secret api_encryption_key

ota:
  - platform: esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

uart:
  id: rs485_bus
  tx_pin: GPIO19
  rx_pin: GPIO22
  baud_rate: 57600
  data_bits: 8
  stop_bits: 1
  parity: NONE
  debug:
    direction: RX
    dummy_receiver: true
    after:
      timeout: 500ms
    sequence:
      - lambda: |-
          std::string data;
          for (auto c : bytes) {
            if (c >= 32 && c < 127) data += static_cast<char>(c);
          }
          id(response_buffer) += data;

          size_t pos;
          while ((pos = id(response_buffer).find("</iZS10.3>")) != std::string::npos) {
            std::string response = id(response_buffer).substr(0, pos + 10);
            id(response_buffer) = id(response_buffer).substr(pos + 10);

            ESP_LOGI("AC", "RX: %s", response.c_str());

            if (response.find("<request>setZoneData</request>") != std::string::npos) {
              int zone_id = 0;
              auto zone_start = response.find("<zone");
              if (zone_start != std::string::npos) {
                for (int i = 0; i < 20 && zone_start + i < response.size(); i++) {
                  char c = response[zone_start + i];
                  if (c >= '0' && c <= '9') {
                    zone_id = c - '0';
                    break;
                  }
                  if (c == '>') break;
                }
              }

              auto extract = [&](const std::string& tag) {
                auto start = response.find("<" + tag + ">", zone_start);
                if (start == std::string::npos || start > response.size()) return std::string("");
                auto end = response.find("</" + tag + ">", start);
                if (end == std::string::npos || end > response.size()) return std::string("");
                return response.substr(start + tag.size() + 2, end - start - tag.size() - 2);
              };

              std::string setting = extract("setting");
              std::string percent = extract("userPercentSetting");
              std::string temp = extract("desiredTemp");

              ESP_LOGI("AC", "=== SET Zone %d ===", zone_id);
              if (!setting.empty()) ESP_LOGI("AC", "  setting: %s", setting.c_str());
              if (!percent.empty()) ESP_LOGI("AC", "  userPercentSetting: %s", percent.c_str());
              if (!temp.empty()) ESP_LOGI("AC", "  desiredTemp: %s", temp.c_str());
            }

            if (response.find("<request>setSystemData</request>") != std::string::npos) {
              auto extract = [&](const std::string& tag) {
                auto start = response.find("<" + tag + ">");
                if (start == std::string::npos) return std::string("");
                auto end = response.find("</" + tag + ">", start);
                if (end == std::string::npos) return std::string("");
                return response.substr(start + tag.size() + 2, end - start - tag.size() - 2);
              };

              std::string power = extract("airconOnOff");
              std::string mode = extract("mode");
              std::string fan = extract("fanSpeed");
              std::string temp = extract("centralDesiredTemp");

              ESP_LOGI("AC", "=== SET SYSTEM ===");
              if (!power.empty()) ESP_LOGI("AC", "  power: %s", power.c_str());
              if (!mode.empty()) ESP_LOGI("AC", "  mode: %s", mode.c_str());
              if (!fan.empty()) ESP_LOGI("AC", "  fanSpeed: %s", fan.c_str());
              if (!temp.empty()) ESP_LOGI("AC", "  centralDesiredTemp: %s", temp.c_str());
            }
          }

globals:
  - id: response_buffer
    type: std::string
    initial_value: '""'
